package com.borrowly.model.item;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.*;

class ItemTest {

    private Validator validator;

    @BeforeEach
    void setUp() {
        // Standalone Jakarta validator, so @NotBlank/@Size/@DecimalMin can be checked without a database
        try (ValidatorFactory factory = Validation.buildDefaultValidatorFactory()) {
            validator = factory.getValidator();
        }
    }

    @Test
    void builder_ProducesExpectedValues() {
        UUID id = UUID.randomUUID();
        Item item = Item.builder()
                .id(id)
                .title("Cordless drill")
                .description("18V, two batteries included")
                .pricePerDay(new BigDecimal("5.00"))
                .depositAmount(new BigDecimal("50.00"))
                .finePerDay(new BigDecimal("2.50"))
                .condition(ItemCondition.GOOD)
                .status(ItemStatus.RENTED)
                .build();

        // The builder transforms nothing, so every getter returns what we passed in
        assertEquals(id, item.getId());
        assertEquals("Cordless drill", item.getTitle());
        assertEquals("18V, two batteries included", item.getDescription());
        assertEquals(new BigDecimal("5.00"), item.getPricePerDay());
        assertEquals(new BigDecimal("50.00"), item.getDepositAmount());
        assertEquals(new BigDecimal("2.50"), item.getFinePerDay());
        assertEquals(ItemCondition.GOOD, item.getCondition());
        assertEquals(ItemStatus.RENTED, item.getStatus()); // explicit value beats @Builder.Default
    }

    @Test
    void builder_PopulatesDefaults() {
        Item item = Item.builder().build();

        assertNotNull(item.getId(), "Id should be generated by the builder"); // @Builder.Default keeps the field initializer
        assertEquals(ItemStatus.ACTIVE, item.getStatus(), "A new item should default to ACTIVE");
    }

    @Test
    void validation_PassesForValidItem() {
        // Baseline: the helper satisfies every constraint, so nothing is reported
        assertTrue(validator.validate(validItemBuilder().build()).isEmpty());
    }

    @Test
    void validation_TriggersWhenRequiredFieldsMissing() {
        Item item = Item.builder()
                .title("Cordless drill")
                .build();

        // @NotNull fires on all four; status is missing from the set because its default already ran
        assertEquals(
                Set.of("pricePerDay", "depositAmount", "finePerDay", "condition"),
                violatedFields(item));
    }

    @Test
    void validation_TriggersOnBlankTitle() {
        Item item = validItemBuilder().title("   ").build();

        assertTrue(violatedFields(item).contains("title")); // @NotBlank rejects whitespace-only
    }

    @Test
    void validation_TriggersOnTitleLength() {
        Item tooShort = validItemBuilder().title("ab").build();
        Item tooLong = validItemBuilder().title("a".repeat(121)).build();

        // Both ends of @Size(min = 3, max = 120)
        assertTrue(violatedFields(tooShort).contains("title"), "Title below 3 characters should be rejected");
        assertTrue(violatedFields(tooLong).contains("title"), "Title above 120 characters should be rejected");
    }

    @Test
    void validation_TriggersOnTooLongDescription() {
        Item item = validItemBuilder().description("a".repeat(4001)).build();

        assertTrue(violatedFields(item).contains("description")); // one past @Size(max = 4000)
    }

    @Test
    void validation_TriggersOnNegativeAmounts() {
        Item item = validItemBuilder()
                .pricePerDay(new BigDecimal("-0.01"))
                .depositAmount(new BigDecimal("-1.00"))
                .finePerDay(new BigDecimal("-10.00"))
                .build();

        // @DecimalMin("0.00") fires on each; the exact set proves nothing else broke
        assertEquals(Set.of("pricePerDay", "depositAmount", "finePerDay"), violatedFields(item));
    }

    @Test
    void validation_TriggersOnTooManyDecimalPlaces() {
        Item item = validItemBuilder().pricePerDay(new BigDecimal("5.999")).build();

        assertTrue(violatedFields(item).contains("pricePerDay")); // @Digits(fraction = 2); Postgres would silently round this
    }

    @Test
    void validation_AllowsZeroAmounts() {
        Item item = validItemBuilder()
                .pricePerDay(BigDecimal.ZERO)
                .depositAmount(BigDecimal.ZERO)
                .finePerDay(BigDecimal.ZERO)
                .build();

        // Zero sits on the boundary and is allowed, so free rentals stay legal
        assertTrue(validator.validate(item).isEmpty(), "@DecimalMin(\"0.00\") is inclusive, so zero is valid");
    }

    @Test
    void equalsAndHashCode_ComparesByIdOnly() {
        UUID sharedId = UUID.randomUUID();

        Item item = validItemBuilder().id(sharedId).title("Cordless drill").build();
        Item sameIdDifferentTitle = validItemBuilder().id(sharedId).title("Angle grinder").build();
        Item differentIdSameTitle = validItemBuilder().id(UUID.randomUUID()).title("Cordless drill").build();

        assertEquals(item, sameIdDifferentTitle); // only id is @Include'd, so title is ignored
        assertEquals(item.hashCode(), sameIdDifferentTitle.hashCode());
        assertNotEquals(item, differentIdSameTitle); // different id, so not equal despite same title
    }

    private Item.ItemBuilder validItemBuilder() {
        return Item.builder()
                .title("Cordless drill")
                .description("18V, two batteries included")
                .pricePerDay(new BigDecimal("5.00"))
                .depositAmount(new BigDecimal("50.00"))
                .finePerDay(new BigDecimal("2.50"))
                .condition(ItemCondition.GOOD);
    }

    private Set<String> violatedFields(Item item) {
        return validator.validate(item).stream()
                .map(ConstraintViolation::getPropertyPath)
                .map(Object::toString)
                .collect(Collectors.toSet());
    }
}