spring.application.name=borrowly
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.expiration=${JWT_EXPIRATION:86400000}

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=50